sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"
sylius_admin_newsletter:
    resource: |
        alias: sylius.newsletter
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: sylius_admin_newsletter
        permission: true
        vars:
            all:
                subheader: sylius.ui.newsletters
                templates:
                    form: "@SyliusAdmin/Newsletter/_form.html.twig"
            index:
                icon: star
    type: sylius.resource
    prefix: admin
sylius_admin_customer_newsletter:
    resource: |
        alias: sylius.customer_newsletter
        section: admin
        templates: "@SyliusAdmin\\Crud"
        grid: sylius_admin_customer_newsletter
        permission: true
        only: [index]
        vars:
            all:
                subheader: sylius.ui.customer_newsletters
            index:
                icon: star
    type: sylius.resource
    prefix: admin
